# Generated by Django 5.0.6 on 2024-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.TextField(choices=[('Работа', 'Work'), ('Семья', 'Family'), ('Личное', 'Personal'), ('Дом', 'Home'), ('Здоровье', 'Health'), ('Деньги', 'Money')], default='Разное'),
        ),
    ]
