# Generated by Django 5.0.6 on 2024-06-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.TextField(choices=[('Работа', 'Work'), ('Семья', 'Family'), ('Личное', 'Personal'), ('Дом', 'Home'), ('Здоровье', 'Health'), ('Деньги', 'Money')], default='Другое'),
        ),
    ]
