# Generated by Django 5.0.6 on 2024-10-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_done_alter_notes_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
